version: '3.1'

services:
  sample-service:
    build:
      context: ./sample-service
    restart: always

  openig:
    image: openidentityplatform/openig:latest
    volumes:
      - ./openig-config:/usr/local/openig-config
    environment:
      CATALINA_OPTS: -Dopenig.base=/usr/local/openig-config -Dendpoint.api=http://sample-service:8080/
    ports:
      - "8080:8080"

